name: Deploy Artifact Registry Cleanup Policies
on:
  push:
    branches:
      - "*"

jobs:
  deploy-artifactregistry-mystic-parking:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "deploy_config"
        run: >
          gcloud
          artifacts
          repositories
          set-cleanup-policies
          gcf-artifacts
          --project=twin-villas
          --location=us-east4
          --policy=gcp/artifactregistry/delete_policy.json
          --no-dry-run
