name: Deploy Dev API Gateway
on:
  push:
    branches:
      - "*"
      - "!main"
    paths:
      - "gcp/apigateway/mysticparking-dev/openapispec.yaml"

jobs:
  deploy-apigateway-mysticparking-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "create_config"
        run: >
          gcloud
          api-gateway
          api-configs
          create
          mysticparking-dev-config-${{ steps.date.outputs.date }}
          --api=mysticparking
          --openapi-spec=gcp/apigateway/mysticparking-dev/openapispec.yaml
          --project=twin-villas
      - id: "deploy_config"
        run: >
          gcloud
          api-gateway
          gateways
          update
          mysticparking-dev
          --api=mysticparking
          --api-config=mysticparking-dev-config-${{ steps.date.outputs.date }}
          --location=us-east4
          --project=twin-villas
