name: Deploy API Gateway
on:
  push:
    branches:
      - main
    paths:
      - "gcp/apigateway/mystic-parking/openapispec.yaml"

jobs:
  deploy-apigateway-mystic-parking:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "create_config"
        run: >
          gcloud
          api-gateway
          api-configs
          create
          mystic-parking-config-${{ steps.date.outputs.date }}
          --api=mystic-parking
          --openapi-spec=gcp/apigateway/mystic-parking/openapispec.yaml
          --project=mystic-parking
      #- id: "create_gateway"
      #  run: >
      #    gcloud
      #    api-gateway
      #    gateways
      #    create
      #    mystic-parkinggateway
      #    --api=mystic-parking
      #    --api-config=mystic-parking-config-${{ steps.date.outputs.date }}
      #    --project=mystic-parking
      #    --location=us-east4
      - id: "deploy_config"
        run: >
          gcloud
          api-gateway
          gateways
          update
          mystic-parkinggateway
          --api=mystic-parking
          --api-config=mystic-parking-config-${{ steps.date.outputs.date }}
          --location=us-east4
          --project=mystic-parking
