name: Run Checks (Dev)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  firebaseApiKey: ${{ secrets.firebaseApiKey }}
  firebaseAppId: ${{ secrets.firebaseAppId }}
  firebaseAuthDomain: ${{ secrets.firebaseAuthDomain }}
  firebaseProjectId: ${{ secrets.firebaseProjectId }}
  firebaseStoreBucket: ${{ secrets.firebaseStoreBucket }}
  firebaseMessagingSenderId: ${{ secrets.firebaseMessagingSenderId }}
  API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  dev-tests:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        run: yarn install

      - name: Prettier
        run: yarn run format
      #- name: Validate OpenAPI definition
      #  uses: char0n/swagger-editor-validate@v1
      #  with:
      #    definition-file: pages/api/openapispec.yaml
      - name: Lint
        run: yarn run lint
      #- name: Cypress run
      #  uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      #  with:
      #    start: yarn run dev
      #    record: true
      #  env:
      #    # pass the Dashboard record key as an environment variable
      #    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #    CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Preview Deployment Available At**
            ${{ env.PREVIEW_URL }}
